# Generated by Django 4.1.3 on 2022-11-24 01:19

from django.db import migrations


# This is the function that creates the first 3 tiers on start
def create_account_tiers(apps, schema_editor):
    AccountTier = apps.get_model('home', 'AccountTier')
    ImageThumbnail = apps.get_model('home', 'ImageThumbnail')
    AccountTier.objects.create(
        name="BASIC",
    )
    ImageThumbnail.objects.create(
        account_tier=AccountTier.objects.get(name="BASIC"),
        height="200"
    )
    AccountTier.objects.create(
        name="PREMIUM",
        display_link_to_original_image=True
    )
    ImageThumbnail.objects.create(
        account_tier=AccountTier.objects.get(name="PREMIUM"),
        height="200"
    )
    ImageThumbnail.objects.create(
        account_tier=AccountTier.objects.get(name="PREMIUM"),
        height="400"
    )
    AccountTier.objects.create(
        name="ENTERPRISE",
        display_link_to_original_image=True,
        generate_expiring_links=True
    )
    ImageThumbnail.objects.create(
        account_tier=AccountTier.objects.get(name="ENTERPRISE"),
        height="200"
    )
    ImageThumbnail.objects.create(
        account_tier=AccountTier.objects.get(name="ENTERPRISE"),
        height="400"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_account_tiers)
    ]
